:construction: added get_platform boilerplate.

diff --git a/bin/install b/bin/install
--- a/bin/install
+++ b/bin/install
@@ -3,6 +3,25 @@
 set -e
 set -o pipefail
 
+[ -n "$ASDF_INSTALL_VERSION" ] || (>&2 echo 'Missing ASDF_INSTALL_VERSION' && exit 1)
+[ -n "$ASDF_INSTALL_PATH" ] || (>&2 echo 'Missing ASDF_INSTALL_PATH' && exit 1)
+
+get_platform () {
+	local platform="$(uname | tr '[:upper:]' '[:lower:]')"
+
+	case "$platform" in
+		linux|darwin|freebsd)
+			echo "Platform '${platform}' supported!" >&2
+			;;
+		*)
+			echo "Platform '${platform}' not supported!" >&2
+			exit 1
+			;;
+	esac
+
+	echo -n $platform
+}
+
 get_arch () {
 	local arch=""
 
